pipeline {

    agent any

    stages {

        stage('Project Information') {

            steps {

                echo 'Starting Company DevOps Project Pipeline'

            }

        }

        stage('Check Workspace') {

            steps {

                sh 'pwd'
                sh 'ls'

            }

        }

        stage('Check Docker') {

            steps {

                sh 'docker --version'

            }

        }

        stage('Build Docker Image') {

            steps {

                sh 'docker build -t company-devops-project:v1 app'

            }

        }

        stage('Stop Old Container') {

            steps {

                sh 'docker stop company-devops-container || true'

            }

        }

        stage('Remove Old Container') {

            steps {

                sh 'docker rm company-devops-container || true'

            }

        }

        stage('Run New Container') {

            steps {

                sh 'docker run -d --name company-devops-container -p 8088:80 company-devops-project:v1'

            }

        }

    }

}
