pipeline {

    agent any

    environment {
        IMAGE_NAME = "arbaz186/company-devops-project"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Project Information') {
            steps {
                echo 'Starting Company DevOps CI/CD Pipeline'
            }
        }

        stage('Check Docker') {
            steps {
                sh 'docker --version'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} app'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push ${IMAGE_NAME}:${IMAGE_TAG}'
            }
        }

        stage('Update Kubernetes') {
            steps {
                sh '''
                sed -i "s|image:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|g" kubernetes/deployment.yaml
                kubectl apply -f kubernetes/deployment.yaml
                '''
            }
        }

    }

    post {
        success {
            echo 'Deployment Successful'
        }

        failure {
            echo 'Deployment Failed'
        }
    }

}
