pipeline {

    agent any

    stages {

        stage('Project Information') {

            steps {

                echo 'Starting Company DevOps Project Pipeline'

            }

        }

        stage('Check Workspace') {

            steps {

                sh 'pwd'
                sh 'ls'

            }

        }

        stage('Check Docker') {

            steps {

                sh 'docker --version'

            }

        }

    }

}
